[package]
name = "actix-web-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.1"
bytes = "1.5.0"
futures-util = "0.3.30"
tokio = { version = "1.35.1", features = ["time"] }
